{
 "title": "Kubestash V2 Monitoring",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "cluster",
    "label": "Cluster",
    "query": {
     "query": "label_values(kubestash_v2_settings_total, cluster)"
    }
   },
   { "name": "cluster_k8", "label": "Cluster Name", "query": "stage" },
   {
    "name": "node_ip",
    "label": "Node IP",
    "query": {
     "query": "label_values(kubestash_v2_settings_total{cluster=\"$cluster\"}, node_ip)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Kubestash Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Kubestash V2 Config",
   "type": "table",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "kubestash_v2_settings_total{cluster=\"$cluster\"}"
    }
   ]
  },
  {
   "title": "Time to Sync Secret by Each Call",
   "type": "timeseries",
   "description": "Each spike tells time taken by kubestash v2 to sync",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "idelta(kubestash_ddb_fetch_seconds_sum{cluster=\"$cluster\"}[20s])"
    }
   ]
  },
  {
   "title": "Partial Key Update ",
   "type": "timeseries",
   "description": "0 - OK \n1 - Failed\nCheck kubestash cron logs to debug.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 11 },
   "targets": [
    {
     "expr": "avg(rate(kubestash_key_synced_failed_status{cluster=\"$cluster\"}[1m])) by (k8s_pod)",
     "legendFormat": "{{k8s_pod}}"
    }
   ]
  },
  {
   "title": "Request count By Code",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
   "targets": [
    {
     "expr": "kubestash_200_request_count_total{cluster=\"$cluster\"}",
     "legendFormat": "200"
    },
    {
     "expr": "kubestash_400_request_count_total{cluster=\"$cluster\"}",
     "legendFormat": "400"
    },
    {
     "expr": "kubestash_404_request_count_total{cluster=\"$cluster\"}",
     "legendFormat": "404"
    },
    {
     "expr": "kubestash_429_requests_count_total{cluster=\"$cluster\"}",
     "legendFormat": "429"
    },
    {
     "expr": "kubestash_500_request_count_total{cluster=\"$cluster\"}",
     "legendFormat": "500"
    }
   ]
  },
  {
   "title": "Credstash Fetch Operation Stuck Status",
   "type": "timeseries",
   "description": "0 - OK \n1 - Failed\nCheck kubestash cron logs to debug.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 19 },
   "targets": [
    {
     "expr": "avg(rate(kubestash_table_fetch_status[1m])) by (cluster, k8s_pod)",
     "legendFormat": "{{cluster}} | {{k8s_pod}}"
    }
   ]
  },
  { "title": "Pod Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 } },
  {
   "title": "CPU Usage for Pod",
   "type": "timeseries",
   "description": "Higher Usage % indicates usage is more than requests.",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{name!~\".*prometheus.*\", image!=\"\", container_name!=\"POD\", namespace=\"kubestash-v2\", cluster=\"$cluster_k8\"}[5m])) by (pod)\n/sum(container_spec_cpu_quota{name!~\".*prometheus.*\", image!=\"\", container_name!=\"POD\", namespace=\"kubestash-v2\", cluster=\"$cluster_k8\"}\n  /container_spec_cpu_period{name!~\".*prometheus.*\", image!=\"\", container_name!=\"POD\", namespace=\"kubestash-v2\", cluster=\"$cluster_k8\"}) by (pod)  * 100",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Memory Usage for Pod",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum(container_memory_usage_bytes{ namespace=\"kubestash-v2\", cluster=\"$cluster_k8\"}) by (namespace, pod) / sum(container_spec_memory_limit_bytes{ namespace=\"kubestash-v2\", cluster=\"$cluster_k8\"}) by (namespace, pod) * 100",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Running Pod Count",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 37 },
   "targets": [
    {
     "expr": "avg(kube_pod_container_status_ready{namespace=\"kubestash-v2\"}) by (cluster)",
     "legendFormat": "{{cluster}}"
    }
   ]
  },
  {
   "title": "Restart Count by Pod",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 37 },
   "targets": [
    {
     "expr": "(sum(increase(kube_pod_container_status_restarts_total{namespace=\"kubestash-v2\", cluster=\"$cluster_k8\"}[10m])) by (pod))",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Pod Termination Reason",
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 46 },
   "targets": [
    {
     "expr": "sum(kube_pod_container_status_last_terminated_reason{namespace=\"kubestash-v2\", cluster=\"$cluster_k8\"}) by (reason, pod)"
    }
   ]
  },
  { "title": "Node Status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 53 } },
  {
   "title": "Node CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 - (avg by (instance) (irate(node_cpu_seconds_total{instance=\"${node_ip}:9100\",mode=\"idle\"}[5m])) * 100)",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  {
   "title": "Node Memory Usage",
   "type": "timeseries",
   "description": "Memory Usage on which Kubestash v2 is running",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(1-node_memory_MemAvailable_bytes{instance=\"${node_ip}:9100\"}/node_memory_MemTotal_bytes{instance=\"${node_ip}:9100\"})*100 or (1-node_memory_MemAvailable{instance=\"${node_ip}:9100\"}/node_memory_MemTotal{instance=\"${node_ip}:9100\"})*100",
     "legendFormat": "{{instance}}"
    }
   ]
  }
 ]
}