apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "kubestash-v2.fullname" . }}
  labels: 
    {{- include "kubestash-v2.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "kubestash-v2.fullname" . }}
subjects:
- kind: ServiceAccount
  name: {{ include "kubestash-v2.serviceAccountName" . }}
  namespace: {{ .Values.namespace }}
